### ISSUE TITLE
[Deprecated] FormPositionExtension + ButtonPositionExtension need to implement `static getExtendedTypes()`

### ISSUE THREAD

**Issue by keichinger** [Becklyn/OrderedFormBundle#2]
The interface `Symfony\Component\Form\FormTypeExtensionInterface` has been updated with a new deprecation warning that the current `getExtendedType` method will be removed in favour of the new `static getExtendedTypes()` method. 

Until Symfony 5 has been released, we need to implement both methods.

**Comment by klapaudius** [comment]
Hi, I did a PR and it did been merged but a composer update still download the old code. Can you make a new release to get ride of the deprecated warnings ?

**Comment by keichinger** [comment]
Hi @klapaudius,

good point! I've just released v1.1.0, which includes your changes.

**Comment by klapaudius** [comment]
Thanks 👍
